<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<UseWPF>true</UseWPF>

		<OutputType>WinExe</OutputType>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>

		<RootNamespace>SCG</RootNamespace>
		<AssemblyName>SourceControlGenerator</AssemblyName>

		<AssemblyTitle>Source Control Generator</AssemblyTitle>
		<AssemblyProduct>Source Control Generator</AssemblyProduct>
		<AssemblyDescription>Generate git repositories for mod projects with a centralized interface.</AssemblyDescription>
		<AssemblyCompany>LaughingLeader</AssemblyCompany>
		<AssemblyCopyright>Copyright © LaughingLeader 2018</AssemblyCopyright>
		<AssemblyVersion>1.7.10.1</AssemblyVersion>
		<AssemblyFileVersion>1.7.10.1</AssemblyFileVersion>

		<ApplicationIcon>AppIcon.ico</ApplicationIcon>
		<StartupObject>SCG.App</StartupObject>
	</PropertyGroup>

	<ItemGroup Label="Global Usings">
		<Using Include="ReactiveUI" />
		<Using Include="ReactiveUI.Fody.Helpers" />
		<Using Include="System.Reactive" />
		<Using Include="System.Reactive.Concurrency" />
		<Using Include="System.Reactive.Concurrency" />
		<Using Include="System.Reactive.Disposables" />
		<Using Include="System.Reactive.Linq" />
		<Using Include="System.Threading" />
		<Using Include="System.Threading.Tasks" />
		<Using Include="System.IO" />
		<Using Include="ReactiveUI.ReactiveCommand&lt;System.Reactive.Unit, System.Reactive.Unit&gt;" Alias="RxCommandUnit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
		<ProjectReference Include="..\MarkdownConverter\MarkdownConverter.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ControlzEx" Version="6.0.0" />
		<PackageReference Include="ReactiveUI" Version="20.1.63" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
		<PackageReference Include="ReactiveHistory" Version="0.10.7" />
		<PackageReference Include="ReactiveUI.Events.WPF" Version="15.1.1" />
		<PackageReference Include="ReactiveUI.WPF" Version="20.1.63" />
		<PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
		<PackageReference Include="SharpCompress" Version="0.38.0" />
		<PackageReference Include="WriteableBitmapEx" Version="1.6.8" />
		<PackageReference Include="Markdig" Version="0.37.0" />
		<PackageReference Include="Extended.Wpf.Toolkit" Version="4.6.1" />
		<PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets="all" />
		<PackageReference Include="DynamicData" Version="9.0.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Splat" Version="15.2.22" />
		<PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
		<PackageReference Include="MdXaml" Version="1.27.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\**" />
	</ItemGroup>

	<Target Name="AfterBuild">
		<ItemGroup>
			<MoveToLibFolder Include="$(OutputPath)*.dll ; $(OutputPath)*.pdb ; $(OutputPath)*.xml" />
		</ItemGroup>
		<Move SourceFiles="@(MoveToLibFolder)" DestinationFolder="$(OutputPath)_Lib" OverwriteReadOnlyFiles="true" />
	</Target>
</Project>