<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Common.props" />
	
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		
		<UseWPF>true</UseWPF>

		<OutputType>WinExe</OutputType>

		<RootNamespace>SCG</RootNamespace>
		<AssemblyName>SourceControlGenerator</AssemblyName>

		<AssemblyTitle>Source Control Generator</AssemblyTitle>
		<AssemblyProduct>Source Control Generator</AssemblyProduct>
		<AssemblyDescription>Generate git repositories for mod projects with a centralized interface.</AssemblyDescription>
		<AssemblyCompany>LaughingLeader</AssemblyCompany>
		<AssemblyCopyright>Copyright © LaughingLeader 2018</AssemblyCopyright>
		<AssemblyVersion>1.7.10.1</AssemblyVersion>
		<AssemblyFileVersion>1.7.10.1</AssemblyFileVersion>

		<ApplicationIcon>AppIcon.ico</ApplicationIcon>
		<StartupObject>SCG.Program</StartupObject>

		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>$(SolutionDir)\bin\$(Configuration)\</OutputPath>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
		<ProjectReference Include="..\MarkdownConverter\MarkdownConverter.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ControlzEx" Version="6.0.0" />
		<PackageReference Include="ReactiveUI" Version="20.1.63" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
		<PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets="all" />
		<PackageReference Include="ReactiveHistory" Version="0.10.7" />
		<PackageReference Include="ReactiveUI.Events.WPF" Version="15.1.1" />
		<PackageReference Include="ReactiveUI.WPF" Version="20.1.63" />
		<PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
		<PackageReference Include="SharpCompress" Version="0.38.0" />
		<PackageReference Include="WriteableBitmapEx" Version="1.6.8" />
		<PackageReference Include="Markdig" Version="0.37.0" />
		<PackageReference Include="Extended.Wpf.Toolkit" Version="4.6.1" />
		<PackageReference Include="DynamicData" Version="9.0.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Splat" Version="15.2.22" />
		<PackageReference Include="Splat.DependencyInjection.SourceGenerator" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" Version="1.2.3" />
		<PackageReference Include="LazyCache.Splat" Version="1.0.0" />
		<PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
		<PackageReference Include="MdXaml" Version="1.27.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\**" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Publish' or '$(Configuration)' == 'PublishTest'">
		<TidyRelease>True</TidyRelease>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TidyRelease)' == True">
		<PreBuildEvent>rd /s /q $(TargetDir)_Lib</PreBuildEvent>
	</PropertyGroup>

	<!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<LSLib Include="$(SolutionDir)External\lslib\Ijwhost.dll; $(SolutionDir)External\lslib\LSLib.dll; $(SolutionDir)External\lslib\LSLibNative.dll; $(SolutionDir)External\lslib\LZ4.dll; $(SolutionDir)External\lslib\LZ4pn.dll; $(SolutionDir)External\lslib\OpenTK.Mathematics.dll; $(SolutionDir)External\lslib\System.IO.Hashing.dll; $(SolutionDir)External\lslib\ZstdSharp.dll;" />
		</ItemGroup>
		<Copy SourceFiles="@(LSLib)" DestinationFolder="$(SolutionDir)bin\$(Configuration)\_Lib\" OverwriteReadOnlyFiles="true" />
	</Target>-->

	<Target Name="SetupLibFolder" AfterTargets="AfterBuild" Condition="'$(TidyRelease)' == True">
		<ItemGroup>
			<DeleteDebug Include="$(OutputPath)*.pdb" />
			<MoveToLibFolder Include="$(OutputPath)*.dll;$(OutputPath)*.xml" />
		</ItemGroup>
		<Delete Files="@(DeleteDebug)">
			<Output TaskParameter="DeletedFiles" ItemName="DeletedList" />
		</Delete>
		<RemoveDir Directories="$(OutputPath)de;$(OutputPath)en;$(OutputPath)es;$(OutputPath)fr;$(OutputPath)it;$(OutputPath)ja;$(OutputPath)ko;$(OutputPath)ru;$(OutputPath)zh-Hans;$(OutputPath)zh-Hant;$(OutputPath)cs-CZ;$(OutputPath)hu;$(OutputPath)ja-JP;$(OutputPath)pt-BR;$(OutputPath)ro;$(OutputPath)runtimes;$(OutputPath)sv" />
		<Move SourceFiles="@(MoveToLibFolder)" DestinationFolder="$(OutputPath)_Lib" OverwriteReadOnlyFiles="true" ContinueOnError="true" />
	</Target>
</Project>