<Project>
	<Import Project="..\Common.props" />

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup Label="Mod Global Usings">
		<Using Include="SCG.Services" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Utilities\Utilities.csproj" Private="False" />
		<ProjectReference Include="..\..\GUI\GUI.csproj" Private="False" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Splat" Version="15.2.22" PrivateAssets="all" ExcludeAssets="runtime" />
		<PackageReference Include="Splat.DependencyInjection.SourceGenerator" PrivateAssets="all" ExcludeAssets="runtime" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" Version="1.2.3" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
		<PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets="all" />
	</ItemGroup>

	<Target Name="PostBuildCopyModule" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<FilesToMove Include="$(OutputPath)$(AssemblyName).dll" />
		</ItemGroup>
		<Copy SourceFiles="@(FilesToMove)" DestinationFolder="$(SolutionDir)bin\$(Configuration)\Modules\" OverwriteReadOnlyFiles="true" />
	</Target>
</Project>