//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LL.DOS2.SourceControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LL.DOS2.SourceControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Levels
        ///######################
        ///Mods/ModName_GUID/Levels/*
        ///Mods/ModName_GUID/Globals/*
        ///Editor/Mods/ModName_GUID/Levels/*
        ///
        ///#Compiled Story files
        ///######################
        ///*.div
        ///*.raw
        ///
        ///#Assets
        ///######################*
        ///Public/ModName_GUID/Assets/*
        ///#Public/ModName_GUID/GUI/*
        ///
        ///#Editor files
        ///######################
        ///StatsEditorConfig.xml
        ///DockPanel.config
        ///EditorBrowserMetadata.*
        ///EffectEditorConfig.xml
        ///
        ///#Assets
        ///######################
        ///*.gr2
        ///*.dae
        ///*.swf
        ///*.bullet
        ///*.dds
        ///*.tga
        ///*.png
        ///*.ttf
        ///
        ///# L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultGitIgnore {
            get {
                return ResourceManager.GetString("DefaultGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Keywords
        ///#ProjectName = The name of the project, without the GUID.
        ///#ProjectGUID = Just the GUID of the project.
        ///
        ///
        ///#Directories to scan
        ///
        ///Editor/Mods/ProjectName_ProjectGUID
        ///Mods/ProjectName_ProjectGUID
        ///Projects/ProjectName
        ///Public/ProjectName_ProjectGUID.
        /// </summary>
        public static string DirectoryLayout {
            get {
                return ResourceManager.GetString("DirectoryLayout", resourceCulture);
            }
        }
    }
}
