//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LL.SCG.DOS2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LL.SCG.DOS2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gitignore export-ignore
        ///LICENSE export-ignore
        ///README.md export-ignore
        ///CHANGELOG.md export-ignore.
        /// </summary>
        public static string DefaultAttributes {
            get {
                return ResourceManager.GetString("DefaultAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ProjectName Changelog
        ///=======
        ///# 1.0.0.0
        ///* Initial Release.
        /// </summary>
        public static string DefaultChangelog {
            get {
                return ResourceManager.GetString("DefaultChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #SourceControlGenerator
        ///######################
        ///SourceControlGenerator.json
        ///
        ///#Levels
        ///######################
        ///Mods/$ModFolderName/Levels/*
        ///Mods/$ModFolderName/Globals/*
        ///Editor/Mods/$ModFolderName/Levels/*
        ///
        ///#Compiled Story files
        ///######################
        ///*.div
        ///*.raw
        ///
        ///#Assets
        ///######################*
        ///Public/$ModFolderName/Assets/*
        ///#Public/$ModFolderName/GUI/*
        ///
        ///#Editor files
        ///######################
        ///StatsEditorConfig.xml
        ///EffectEditorConfig.xml
        ///DockPanel.config
        ///EditorBrowserMetadata.*
        ///
        ///#Assets [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultGitIgnore {
            get {
                return ResourceManager.GetString("DefaultGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ProjectName for Divinity: Original Sin 2
        ///=======
        ///
        ///### Features:
        ///
        ///
        ///### Releases
        ///* [Steam Workshop]() 
        ///* [Nexus]()
        ///
        ///### Attribution
        ///- [Divinity: Original Sin 2](http://store.steampowered.com/app/435150/Divinity_Original_Sin_2/), a game by [Larian Studios](http://larian.com/).
        /// </summary>
        public static string DefaultReadme {
            get {
                return ResourceManager.GetString("DefaultReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Keywords
        ///# ProjectName = The name of the project, without the GUID.
        ///# ProjectGUID = The GUID(UUID) of the project.
        ///
        ///#Directories to scan
        ///
        ///Editor/Mods/ProjectName_ProjectGUID
        ///Mods/ProjectName_ProjectGUID
        ///Projects/ProjectName
        ///Public/ProjectName_ProjectGUID.
        /// </summary>
        public static string DirectoryLayout {
            get {
                return ResourceManager.GetString("DirectoryLayout", resourceCulture);
            }
        }
    }
}
