<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Module.props" />

	<PropertyGroup>
		<UseWPF>true</UseWPF>

		<RootNamespace>SCG.BG3</RootNamespace>

		<AssemblyName>SCG.BG3</AssemblyName>
		<AssemblyTitle>Baldur's Gate 3 Support</AssemblyTitle>
		<AssemblyProduct>Baldur's Gate 3 Support</AssemblyProduct>
		<AssemblyDescription>Baldur's Gate 3 support for Source Control Generator.</AssemblyDescription>
		<AssemblyCompany>LaughingLeader</AssemblyCompany>
		<AssemblyCopyright>Copyright © LaughingLeader 2024</AssemblyCopyright>

		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<AssemblyFileVersion>1.0.0.0</AssemblyFileVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\External\lslib\LSLib\LSLib.csproj" />
		<ProjectReference Include="..\..\..\External\lslib\LSLibNative\LSLibNative.vcxproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<LSLib Include="$(OutputPath)LSLib.dll;$(OutputPath)LSLibNative.dll" />
		</ItemGroup>
		<Copy SourceFiles="@(LSLib)" DestinationFolder="$(SolutionDir)bin\$(Configuration)\_Lib\" OverwriteReadOnlyFiles="true" />
	</Target>
</Project>
