<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<PlatformTarget>x64</PlatformTarget>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		
		<RootNamespace>SCG.Markdown</RootNamespace>
		<AssemblyName>SCG.MarkdownConverter</AssemblyName>

		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<AssemblyFileVersion>1.0.0.0</AssemblyFileVersion>
		<AssemblyTitle>MarkdownConverter</AssemblyTitle>
		<ProductName>MarkdownConverter</ProductName>
		<Description>Utilities for converting text to/from Markdown and other formats.</Description>
		<Copyright>Copyright © LaughingLeader 2018</Copyright>
		
		<Optimize>true</Optimize>
		<Platforms>x64</Platforms>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<OutputPath>bin\Debug\</OutputPath>
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<DebugType>full</DebugType>
		<ErrorReport>prompt</ErrorReport>
		<Optimize>false</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<OutputPath>bin\Release\</OutputPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Publish'">
		<OutputPath>bin\Publish\</OutputPath>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="AngleSharp" Version="1.1.2" />
		<PackageReference Include="Markdig" Version="0.37.0" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
	</ItemGroup>
</Project>